# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.3'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [4]:
np.random.random((3,2))

array([[0.34280175, 0.53953636],
       [0.8921332 , 0.01940941],
       [0.45741541, 0.03437668]])

In [5]:
np.random.rand(3,2)

array([[0.46676806, 0.66115763],
       [0.2295524 , 0.44077319],
       [0.03923036, 0.23532027]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [9]:
a1 = np.random.randn(1000, 1000)
print(np.mean(a1))
print(np.std(a1))

0.0014896478703612958
1.0002674086995116


In [8]:
a2 = np.random.standard_normal((1000, 1000))
print(np.mean(a2))
print(np.std(a2))

0.0005728418217289187
1.0001711388447034


In [11]:
a3 = np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))
print(np.mean(a3))
print(np.std(a3))

0.0010091990321803041
1.0002268141544435


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [12]:
np.random.randint(0, 4, (3,2))

array([[2, 2],
       [2, 2],
       [3, 1]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [13]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [14]:
for _ in range(10):
    print(np.random.choice(x, p=[.3, .5, .2]))


b'5 out of 10'
b'2 out of 10'
b'3 out of 10'
b'3 out of 10'
b'2 out of 10'
b'5 out of 10'
b'3 out of 10'
b'3 out of 10'
b'5 out of 10'
b'3 out of 10'


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [15]:
np.random.choice(10,3,replace=False)

array([7, 5, 8])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [16]:
x = np.arange(10)
np.random.shuffle(x)
x

array([8, 7, 1, 2, 4, 9, 6, 0, 5, 3])

In [17]:
# Or
np.random.permutation(x)

array([9, 3, 4, 0, 6, 8, 7, 2, 1, 5])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [19]:
np.random.seed(10)