# Set routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

## Making proper sets

Q1. Get unique elements and reconstruction indices from x. And reconstruct x.

In [3]:
x = np.array([1, 2, 6, 4, 2, 3, 2])
unique_elements, rec_indices = np.unique(x, return_inverse=True)
print(unique_elements)
print(rec_indices)
reconstructed = unique_elements[rec_indices]
print(reconstructed)

[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]


## Boolean operations

Q2. Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [4]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])
np.in1d(x,y)

array([ True,  True, False, False,  True])

Q3. Find the unique intersection of x and y.

In [5]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
np.intersect1d(x,y)

array([0, 1])

Q4. Find the unique elements of x that are not present in y.

In [6]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
np.setdiff1d(x,y)

array([2, 5])

Q5. Find the xor elements of x and y.

In [7]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
np.setxor1d(x,y)

array([2, 4, 5])

In [8]:
np.sort(np.concatenate((np.setdiff1d(x,y), np.setdiff1d(y,x))))

array([2, 4, 5])

Q6. Find the union of x and y.

In [9]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])

In [10]:
np.union1d(x,y)

array([0, 1, 2, 4, 5])

In [11]:
np.sort(np.unique(np.concatenate((x,y))))

array([0, 1, 2, 4, 5])