# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])

In [4]:
np.sort(x, axis=1)

array([[1, 4],
       [1, 3]])

In [6]:
x.sort(axis=1)
x

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [11]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')


In [12]:
np.lexsort((surnames,first_names))

array([1, 2, 0])

Q3. Get the indices that would sort x along the second axis.

In [15]:
x = np.array([[1,4],[3,1]])
x

array([[1, 4],
       [3, 1]])

In [14]:
np.argsort(x, axis=1)

array([[0, 1],
       [1, 0]])

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [20]:
x = np.random.permutation(10)
x

array([4, 8, 6, 3, 2, 0, 7, 1, 5, 9])

In [21]:
np.partition(x,5)

array([0, 2, 1, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x.partition(5)
x

array([0, 2, 1, 3, 4, 5, 6, 7, 8, 9])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [33]:
x = np.random.permutation(10)
x

array([8, 9, 7, 1, 4, 5, 3, 2, 6, 0])

In [34]:
partitioned = np.partition(x, 3)
partitioned

array([0, 1, 2, 3, 4, 5, 9, 7, 6, 8])

In [35]:
indices = np.argpartition(x, 3)
indices

array([9, 3, 7, 6, 4, 5, 1, 2, 8, 0])

In [36]:
np.array_equiv(x[indices], partitioned)

True

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [38]:
x = np.random.permutation(10).reshape(2, 5)
x

array([[7, 5, 1, 6, 9],
       [4, 8, 2, 0, 3]])

In [39]:
np.max(x,1)

array([9, 8])

In [40]:
np.argmax(x,1)

array([4, 1])

In [42]:
np.min(x,1)

array([1, 0])

In [43]:
np.argmin(x,1)

array([2, 3])

Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [44]:
x = np.array([[np.nan, 4], [3, 2]])
x

array([[nan,  4.],
       [ 3.,  2.]])

In [45]:
np.nanmax(x,1)

array([4., 3.])

In [46]:
np.nanargmax(x,1)

array([1, 0])

In [47]:
np.nanmin(x,1)

array([4., 2.])

In [48]:
np.nanargmin(x,1)

array([1, 1])

Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [49]:
x = np.array([[1, 2, 3], [1, 3, 5]])
x

array([[1, 2, 3],
       [1, 3, 5]])

In [50]:
x[x>2]

array([3, 3, 5])

In [51]:
np.nonzero(x>2)

(array([0, 1, 1]), array([2, 1, 2]))

Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [53]:
x = np.array([[1, 2, 3], [1, 3, 5]])
x

array([[1, 2, 3],
       [1, 3, 5]])

In [54]:
np.flatnonzero(x>2)

array([2, 4, 5])

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [55]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x<0, 0, x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [56]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)

array([0, 2, 1, 3])

## Counting

Q12. Get the number of nonzero elements in x.

In [58]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5

In [59]:
len(x[x!=0])

5