# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [4]:
x = [1,2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))
print(np.inner(x, y)) #sum(x[:]*y[:])
print(np.inner(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [7]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [39]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [40]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [41]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)

In [42]:
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [43]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)

In [44]:
np.linalg.qr(x)

(array([[-0.85714287,  0.3942857 ,  0.33142856],
        [-0.42857143, -0.9028571 , -0.03428571],
        [ 0.2857143 , -0.17142858,  0.94285715]], dtype=float32),
 array([[ -14.,  -21.,   14.],
        [   0., -175.,   70.],
        [   0.,    0.,  -35.]], dtype=float32))

Q7. Factor x by Singular Value Decomposition and verify it.

In [45]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)

In [46]:
np.linalg.svd(x, full_matrices=False)

(array([[ 0.,  1.,  0.,  0.],
        [ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 0.,  0.,  1.,  0.]], dtype=float32),
 array([3.      , 2.236068, 2.      , 0.      ], dtype=float32),
 array([[-0.       ,  0.       ,  1.       , -0.       ,  0.       ],
        [ 0.4472136,  0.       ,  0.       ,  0.       ,  0.8944272],
        [-0.       ,  1.       ,  0.       , -0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ,  0.       ]],
       dtype=float32))

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [32]:
x = np.diag((1, 2, 3))

In [33]:
np.linalg.eig(x)[0]

array([1., 2., 3.])

In [35]:
eigenvals = np.linalg.eigvals(x)
eigenvals

array([1., 2., 3.])

In [36]:
eigenvecs = np.linalg.eig(x)[1]
eigenvecs

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q9. Predict the results of the following code.

In [38]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [12]:
x = np.arange(1, 10).reshape((3, 3))

In [10]:
np.linalg.norm(x, 'fro')

16.881943016134134

In [13]:
np.linalg.cond(x, 'fro')

inf

Q11. Calculate the determinant of x.

In [14]:
x = np.arange(1, 5).reshape((2, 2))

In [15]:
np.linalg.det(x)

-2.0000000000000004

In [16]:
x[0,0]*x[1,1] - x[0,1]*x[1,0]

-2

Q12. Calculate the rank of x.

In [20]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.linalg.matrix_rank(x)

4

In [22]:
np.linalg.svd(x)[1].size

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [23]:
x = np.arange(1, 5).reshape((2, 2))

In [24]:
np.linalg.slogdet(x)

(-1.0, 0.6931471805599455)

In [25]:
np.sign(np.linalg.det(x))

-1.0

In [27]:
np.log(np.abs(np.linalg.det(x)))

0.6931471805599455

Q14. Return the sum along the diagonal of x.

In [28]:
x = np.eye(4)

In [29]:
np.trace(x)

4.0

In [31]:
x.diagonal().sum()

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [8]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])